name: Automated tests

on:
  push:
    branches:
      - '*'
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        type: choice
        options:
          - auth_test
          - crud_test
          - varios_data_create

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: install dependencies
        run: pip install -r requirements.txt

      - name: auth_tests
        if: "github.event.inputs.deployment_target == 'auth_test'"
        run: pytest tests/test_CRUD.py::test_auth tests/test_CRUD.py::test_auth_response
      - name: crud_test
        if: "github.event.inputs.deployment_target == 'crud_test'"
        run: pytest tests/test_CRUD.py::test_crud_booking
      - name: varios_data_create
        if: "github.event.inputs.deployment_target == 'varios_data_create'"
        run: pytest tests/test_validation_create.py