name: Automated tests

on:
  push:
    branches:
      - '*'
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default:
        type: choice
        options:
          - auth_test
          - crud_test
          - varios_data_create

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: auth_tests
        if: "github.event.inputs.depluyment_target == 'auth_test'"
        run: pytest tests/test_CRUD.py::test_auth tests/test_CRUD.py::test_auth_response
      - name: crud_test
        if: "github.event.inputs.depluyment_target == 'crud_test'"
        run: pytest tests/test_CRUD.py::test_crud_booking
      - name: varios_data_test
        if: "github.event.inputs.depluyment_target == 'varios_data_create'"
        run: pytest tests/teat_validation_create.py
      - name: Install Allure
        run: |
          sudo apt-get install -y default-jre
          wget https://github.com/allure-framework/allure2/releases/latest/download/allure-2.27.0.tgz
          tar -zxvf allure-2.27.0.tgz
          sudo mv allure-2.27.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure
      - name: Generate Allure report
        run: allure generate allure-results -o allure-report --clean
      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report